backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

publish_mode: editorial_workflow
media_folder: "/static/assets" 
public_folder: "/" 

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    media_folder: "/static/assets/blog" 
    public_folder: "/blog" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Meta Description", name: "metadescription", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "authorname", widget: "select", options: ["None", "Justin", "Seth", "Michelle"]}
      - {label: "Featured Image", name: "featuredImage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "jobs"
    label: "Jobs"
    folder: "src/content/careers"
    public_folder: "/careers" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "job-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Team", name: "team", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Responsibilities", name: "responsibilities", widget: "markdown"}
      - {label: "Skills", name: "skills", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/content/press-media.md"
        label: "Press & Media Page"
        name: "press-media"
        media_folder: "/static/assets/featuredOn"
        public_folder: "/featuredOn"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "press-page"}
          - {label: "Featured On", name: featuredOn, widget: list, fields: [{label: Title, name: title, widget: text}, {label: Image, name: image, widget: image}, {label: Published Date, name: date, widget: datetime}, {label: Link, name: link, widget: text}]}
      - file: "src/content/investors.md"
        label: "Investors Page"
        name: "investors"
        media_folder: "/static/assets/featuredOn"
        public_folder: "/featuredOn"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "press-page"}
          - {label: "Investors", name: investors, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Link, name: link, widget: text}]}
      - file: "src/content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/content/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/content/cryptocurrency-glossary/index.md"
        label: "Cryptocurrency Glossary"
        name: "cryptocurrency-glossary"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "cryptocurrency-glossary-page"}
          - {label: "Last Edit Date", name: "date", widget: "datetime"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/content/changelog/index.md"
        label: "Changelog"
        name: "changelog"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "changelog-page"}
          - {label: "Last Edit Date", name: "date", widget: "datetime"}
          - {label: "Chanelog", name: "body", widget: "markdown"}
      - file: "src/content/privacy/index.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "privacy-page"}
          - {label: "Last Edit Date", name: "date", widget: "datetime"}
          - {label: "Privacy Policy", name: "body", widget: "markdown"}
      - file: "src/content/terms/index.md"
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "terms-page"}
          - {label: "Last Edit Date", name: "date", widget: "datetime"}
          - {label: "Terms", name: "body", widget: "markdown"}
      - file: "src/content/accountant/terms.md"
        label: "Accountant Terms"
        name: "accountant-terms"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "accountant-terms"}
          - {label: "Last Edit Date", name: "date", widget: "datetime"}
          - {label: "Accountant Terms", name: "body", widget: "markdown"}
  - name: "exchanges"
    label: "Exchanges"
    label_singular: "Exchange"
    folder: "src/content/exchanges"
    media_folder: "/static/exchanges" 
    public_folder: "/exchanges" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "exchange-page"}
      - {label: "Exchange Name", name: "title", widget: "string"}
      - {label: "API Instructions", name: "APIinstructions", widget: "markdown"}
      - {label: "CSV Instructions", name: "CSVinstructions", widget: "markdown"}
      - {label: "Exchange Logo", name: "exchangeLogo", widget: image}
      - {label: "Exchange Notice", name: "notice", widget: "string"}
      - {label: "Notice Type", name: "noticeType", widget: "select", options: ["warning", "info"]}
  - name: "partners"
    label: "Partners"
    label_singular: "Partner"
    folder: "src/content/invite"
    create: true
    slug: "{{promoCode}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "invite-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Greeting", name: "greeting", widget: "string", default: "Welcome, X Users!"}
      - {label: "Promo Code", name: "promoCode", widget: "string"}
      - {label: "Video URL", name: "videoURL", widget: "string", default: "https://www.youtube.com/embed/UOESx14TIZY"}
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ''
                required: false
              - widget: image
                name: image
                label: image
                default: '/assets/stackrole.png'
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
                
          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
